### ISSUE TITLE
Your master thesis

### ISSUE THREAD

**Issue by MQ-Jonathan-Xu** [karjamatti/Bayesian-cointegration#1]
Hi Matti, very good your thesis is. I have several queries.
1. How can we obtain equation (3.15) by combining (3.8) and (3.14)? How to select p(\epsilon_1) and how to address the term including \phi?
2. How can we calculate the integration in equation (3.15) because of the prefactor? Also, hwo to calculate the moments of variable \phi?

**Comment by karjamatti** [comment]
Hey Jonathan, thanks for reaching out!

Honestly, now that I look back at it all, I'm having a hard time remembering the details. I do remember working out the math on paper, but this was 2 years ago, and I've been working on something completely different since then so it's difficult to wrap my mind around it all of a sudden. Anyway, the methodology in this part was originally introduced in Bracegirdle & Barber (2012) (https://icml.cc/2012/papers/570.pdf, chapters 2 and 3) so it might be worth checking in with Chris Bracegirdle to discuss the details for both questions.

As for the distribution of the initial residual, it's assumed to be gaussian, with mean zero, and the variance needs to satisfy the recurrence relation to ensure stationarity. Check out the part right before equation 3.13 where this is discussed. As for the (log) moments of phi, check out the function 'Get Moments Log'.

All the best,
Matti
